version: 0.2
phases:
  install:
    runtime-versions:
       nodejs: latest
       python: latest
  pre_build:
    commands:
      - cd ./pixelapp_fe
      - npm install
  build:
    commands:
      - npm run build && cd ../
      - cd ./pixelapp_be
      - echo "{}" > const/aws-config.json 
      - npm install && cd ../
  post_build:
    commands:
      - chmod 700 awscli-workflow.sh
      - ./awscli-workflow.sh
artifacts:
  files:
     - ./pixelapp_fe/build/**/*
