version: 0.2
phases:
  install:
    runtime-versions:
       nodejs: latest
  pre_build:
    commands:
      - ls -la
      - node -v
      - npm -v
      - cd ./pixelapp_fe
      - npm install
      - npm audit fix --force
  build:
    commands:
      - npm run build && cd ../
      - cd ./pixelapp_be
      - npm install 
      - npm audit fix --force && cd ../
  post_build:
    commands:
      - pwd
      - ls -la
artifacts:
  files:
     - ./pixelapp_fe/**/*
