version: 0.2
phases:
  install:
    runtime-versions:
       nodejs: 12
       python: 3.8
  pre_build:
    commands:
      - chmod 700 set_values.sh
      - ./set_values.sh
      - cd ./pixelapp_fe
      - npm install
      - npm audit fix --force
  build:
    commands:
      - npm run build && cd ../
      - cd ./pixelapp_be
      - npm install 
      - npm audit fix --force && cd ../
  post_build:
    commands:
      - chmod 700 awscli-workflow.sh
      - ./awscli-workflow.sh
artifacts:
  files:
     - ./pixelapp_fe/build/**/*
