version: 0.2
phases:
  install:
    runtime-versions:
       nodejs: latest
       python: latest
  pre_build:
    commands:
      - ls -la
      - cd ./pixelapp_fe
      - npm install
      - npm audit fix --force
  build:
    commands:
      - npm run build && cd ../
      - cd ./pixelapp_be
      - npm install 
      - npm audit fix --force && cd ../
  post_build:
    commands:
      - pwd
      - chmod 700 awscli-workflow.sh
      - ls -la
      - ./awscli-workflow.sh
artifacts:
  files:
     - ./pixelapp_fe/build/**/*
